name: Coverity scan build

on:
  workflow_call:
    secrets:
      coverity_api_token:

jobs:
  coverity_build:
    if: github.repository_owner == 'openwrt'
    name: Coverity x86/64 build
    secrets:
      coverity_api_token: ${{ secrets.coverity_api_token }}
    permissions:
      contents: read
      packages: read
      actions: write
    uses: ./.github/workflows/reusable_build.yml
    with:
      container_name: toolchain
      target: x86
      subtarget: 64
      build_full: true
      include_feeds: true
      use_ccache_cache: false
      coverity_compiler_template_list: >-
        x86_64-openwrt-linux-gcc
        x86_64-openwrt-linux-musl-gcc
      #  qosify fails to build with cov-build
      coverity_check_packages: >-
        cgi-io
        dnsmasq
        dropbear
        firewall
        fstools
        fwtool
        iwinfo
        jsonfilter
        libnl-tiny
        libubox
        mtd
        netifd
        odhcp6c
        odhcpd
        opkg
        procd
        relayd
        rpcd
        swconfig
        ubox
        ubus
        ucert
        uci
        uclient
        ucode
        ugps
        uhttpd
        umbim
        umdns
        unetd
        uqmi
        urngd
        usbmode
        usign
        usteer
        ustp
        ustream-ssl
